#!/bin/bash

while getopts ":n:h" arg; do
	case ${arg} in
	n) 
		num=1
		file=$OPTARG
	 	while read line; do
			echo $num\. $line
			((num++))
		done < $file
		;;
	
	h) 
		echo"type -n to display the file lines with numbers"
		;;
	\?) 
		echo"Oops.. Invalid Argument: $OPTARG; use -h for help"
		exit 1
		;;
	:) 	echo" -n needs an argument "
		exit 1
		;;

	esac
exit 0
shift $(( OPTIND -1 ))
done

if [[ $OPTIND -eq 1 ]]; then
	while read line; do 
		echo $line
	done < $1;
exit 0
fi

